import React from 'react';

const VideoGallery = () => {
  return (
      <div style={{ paddingLeft: '120px', backgroundColor: 'white' }}>
 <br></br>
      <h1>Video Gallery</h1>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>      
      <iframe width="300" height="300" src="https://www.youtube.com/embed/-DBvOIUtG54?si=g18Ce13fOdQfRCpW" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/rguV1b4D2Rc?si=grKBlW2HnY8kDL67" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/aB3VATVM1GA?si=bFRbpUsi84-dZCMR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/XzCaWBbBp90?si=CutRH2cp7vbtdrc9" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>      
      <iframe width="300" height="300" src="https://www.youtube.com/embed/IvhSbrk3CbU?si=6dMkDO2TjiuB7vlT" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/b8lKU__3Wks?si=DsCHzElq1o4gcxH7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> 
      <iframe width="300" height="300" src="https://www.youtube.com/embed/5-EGzP7HK5w?si=cDzmpGKCNSwA-BjJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/Ao-63UGSlgE?si=o1TlUYXzHDxDwBIt" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/ceulAo2ZbQQ?si=8mivnMzx5U1WkMlR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/xStzBK50yTQ?si=mdPRMWKzuwtYufM1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/97to42UR_x4?si=c7K1ujteC4lZ9xx_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/cpat3E4TTzU?si=yOAbi_3Y_hiLK4Ox" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/63aaHYYJWnI?si=pmhjQCb5nJw0-jiJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/IgNTqqlyVxM?si=n8lB2MCYh7tfbtg-" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/g8EwDyu6-Tk?si=GbayjcddAuAUchz7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/9SsoXI7NjBM?si=bSn_O-8CnqywN17t" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/Jo7zKZ0MvWI?si=arOLsmUNmM_IA2JI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/Gap4xcAy1NU?si=qembncYYMDxcws8z" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/TH1sPGBy00s?si=Yg6w-9QWYbx80y5d" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/oLibQwy02KM?si=ytvWAgp2ANP5dq5T" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/ljJgLxpD-vo?si=bXMOYMbjJx9UolkN" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/h9O4N1VxR68?si=_kWneuRi45-dBgi8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/cKqqGEi6boY?si=tUFbf4MmzH45pbvP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/CP5ALjn9Qz4?si=BuJrehZb8IOUBUmy" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <iframe width="300" height="300" src="https://www.youtube.com/embed/IIZUE4YfcJE?si=hjTQw9lU46v8gur6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      </div>
    </div>
  );
};

export default VideoGallery;
